# Generated by Django 3.0.7 on 2020-07-11 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participent_name', models.CharField(max_length=100)),
                ('participent_joining_date', models.DateTimeField()),
                ('participent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_series_name', models.CharField(max_length=100)),
                ('test_series_description', models.TextField(blank=True, null=True)),
                ('number_of_tests', models.IntegerField()),
                ('price', models.FloatField()),
                ('test_series_joined', models.BooleanField(default=None)),
                ('test_series_joining_date', models.DateTimeField(blank=True, null=True)),
                ('participent', models.ManyToManyField(blank=True, null=True, related_name='paricipent_set', to='testseriesapp.Participent')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_duration', models.DurationField(blank=True, default='00:05:00', null=True)),
                ('test_max_marks', models.IntegerField(blank=True, null=True)),
                ('number_of_questions', models.IntegerField(null=True)),
                ('test_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseriesapp.TestSeries')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions_attempted', models.IntegerField(blank=True, null=True)),
                ('gained_marks', models.IntegerField()),
                ('minus_marks', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('taken_time', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseriesapp.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('right_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseriesapp.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('choosen_choice', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseriesapp.Question')),
            ],
        ),
    ]
