# Generated by Django 3.0.7 on 2020-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseriesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
