# Generated by Django 3.0.7 on 2020-07-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseriesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participent',
            name='participent_joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
