# Generated by Django 3.0.7 on 2020-07-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testseriesapp', '0002_auto_20200712_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participent',
            name='participent_joining_date',
        ),
        migrations.RemoveField(
            model_name='testseries',
            name='participent',
        ),
        migrations.RemoveField(
            model_name='testseries',
            name='test_series_joined',
        ),
        migrations.RemoveField(
            model_name='testseries',
            name='test_series_joining_date',
        ),
        migrations.CreateModel(
            name='TestSeriesParticipents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participent_joining_date', models.DateTimeField(blank=True, null=True)),
                ('test_series_joined', models.BooleanField(default=None)),
                ('test_series_joining_date', models.DateTimeField(blank=True, null=True)),
                ('participent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseriesapp.Participent')),
                ('testseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseriesapp.TestSeries')),
            ],
        ),
    ]
