# Generated by Django 3.0.7 on 2020-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseriesapp', '0003_test_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='participents',
            field=models.ManyToManyField(blank=True, null=True, related_name='participents', to='testseriesapp.Participent'),
        ),
    ]
