# Generated by Django 3.0.7 on 2020-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseriesapp', '0004_test_participents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='gained_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='minus_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='taken_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
