# Generated by Django 3.0.7 on 2020-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseriesapp', '0004_testseries_participent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testseriesparticipents',
            name='test_series_joined',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
