# Generated by Django 3.0.7 on 2020-07-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseriesapp', '0005_auto_20200712_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choosen_choice',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
